"""empty message

Revision ID: 0f1b23603f0b
Revises: 5cef43e5a1a7
Create Date: 2018-05-05 16:45:43.758669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f1b23603f0b'
down_revision = '5cef43e5a1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender', sa.String(length=20), nullable=False))
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('messages', 'sender')
    # ### end Alembic commands ###
