"""empty message

Revision ID: 5cef43e5a1a7
Revises: cad9550e8724
Create Date: 2018-05-05 16:39:59.496871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cef43e5a1a7'
down_revision = 'cad9550e8724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('messages_ibfk_2', 'messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('messages_ibfk_2', 'messages', 'users', ['sender_id'], ['id'])
    op.alter_column('messages', 'sender_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
