"""empty message

Revision ID: e963458121cd
Revises: 0f1b23603f0b
Create Date: 2018-05-06 18:57:59.941046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e963458121cd'
down_revision = '0f1b23603f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('filesize', sa.Float(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('share', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
